server:
  port: 0

spring:
  application:
    name: ti9-workspace-api
  profiles:
    active: dev
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
config:
  file:
    path: /opt/ti9-workspace-api/config # Linux
    # path: c:/ixml/config # Windows
